spring.application.name=hoodSquare

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=user
spring.datasource.password=secret
spring.datasource.url=jdbc:postgresql://localhost:5080/db
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=wnPAWiKSQFl03btqZFj48VMbKDWx3ih3Hp7iR3R0VMi
app.cors.allowed-origins=http://localhost:5173