spring.application.name=hoodSquare

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=user
spring.datasource.password=secret
spring.datasource.url=jdbc:postgresql://localhost:5080/db
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=MHRgGXa4TS3HIbanb0inBjw7Tdb2MvKwIfNuRw6HJQY=
app.cors.allowed-origins=http://localhost:5173